spring.application.name=lecture_faq_mittmann_fddw
# spring.datasource.url=jdbc:h2:file:./lecture_faq_mittmann_fddw/test_data/user_test_DB

# Der Hostname ist hier der Name des Services im docker-compose

#spring.datasource.url=jdbc:h2:mem:./data/eventDB
spring.datasource.url=jdbc:postgresql://db:5432/postgres

spring.datasource.username=postgres
# Das Passwort muss dem in der docker-compose.yml entsprechen
spring.datasource.password=example
spring.jpa.hibernate.ddl-auto=update
